### ISSUE TITLE
Class Softon\Indipay\Gateways\CCavenueGateway does not exist

### ISSUE THREAD

**Issue by salttechno** [softon/indipay#10]
Hello,

Thank you for the great plugin.

We are trying to setup CCAvenue payment gateway. But on initializing payment, we get following error.

`ReflectionException in Container.php line 734:
Class Softon\Indipay\Gateways\CCavenueGateway does not exist
in Container.php line 734
at ReflectionClass->__construct('Softon\Indipay\Gateways\CCavenueGateway') in Container.php line 734`

I guess issue is with case sensitivity with 'CCavenueGateway' name. File & class name is 'CCAvenueGateway' with capital 'A'. But, I am unable to find location from where 'CCavenueGateway' is getting called.

Older version of Indipay was working fine for CCAvenue.

Regards,
Nilesh G

**Comment by softon** [comment]
use the latest release you can select the Gateway read the readme file

or 

Default is in config/indipay.php

**Comment by salttechno** [comment]
Hello, 

Thank you for responding. 

We are already using latest version. We have also done changes in config/india-news.php as per Readme file.

**Comment by salttechno** [comment]
Sorry, Mobile auto correct changed the spelling of indipay.php in last comment.

**Comment by softon** [comment]
in the config file what is the value of 

'gateway' => 'InstaMojo',                // Replace with the name of default gateway you want to use

have you checked the case in this.

**Comment by salttechno** [comment]
Actually, there is still some issue. My problem got solved when I renamed the file to `CCaveneuGateway.php` from `CCAveneuGateway.php`.

**Comment by softon** [comment]
u never replied to the question
