### ISSUE TITLE
"You do not have permission to perform this action."

### ISSUE THREAD

**Issue by SatyaNarayana-Peddinti** [softon/indipay#11]
I had used the below code in my controller
---------------------------------------------------------
             $parameters = [
              'tid' => '1233221223322',
              'order_id' => '1232212',
              'amount' => '12.00',
              'purpose' => 'Testing',
              'buyer_name' => 'Testing',
              ];
 
            $order = Indipay::prepare($parameters);
            return Indipay::process($order);`
-------------------------------------------------------------
**My output**

           Client error: `POST https://www.instamojo.com/api/1.1/payment-requests/` resulted in a `403       
           FORBIDDEN` response:
           {
             "message": "You do not have permission to perform this action.", 
              "success": false
           }

**Comment by SatyaNarayana-Peddinti** [comment]
Hi again,
I had created a new test account and running my code. Now I am getting a new issue saying that "Invalid Auth Token."

          Client error: `POST https://www.instamojo.com/api/1.1/payment-requests/` resulted in a `401 UNAUTHORIZED` response:
         {
             "success": false, 
             "message": "Invalid Auth Token."
         }

**Comment by softon** [comment]
First you need an account and appropriate keys needs to be set in config file. secondly your account needs to be activated by instamojo. you will have to complete all the formalities.
