### ISSUE TITLE
ebskey is hardcoded into the EBSGateway Class

### ISSUE THREAD

**Issue by IndiaKK** [softon/indipay#12]
In the encrypt function of EBSGateway Class, the "ebskey" string is hard coded into the hash that is generated.  EBS has changed the key and now this is failing with "Invalid Securehash" error.

**Comment by softon** [comment]
ok good u noticed. we will do the correction.

**Comment by softon** [comment]
Solved

**Comment by DhanapalMadheswaran** [comment]
i m getting like this 

SORRY!
We were unable to process your payment


Checksum Failed
