### ISSUE TITLE
IndipayParametersMissingException in PayUMoneyGateway.php 

### ISSUE THREAD

**Issue by Massum** [softon/indipay#16]
` public function bookingconfirm(request $request){
     	
        	 $parameters = [

            'key' => 'RDey6p1q',
            'txnid' => '1233221223322',
            'surl' => 'paymentsuccess',
            'furl' => 'paymentfailure',
            'firstname' => 'massum',
            'email' => 'hussainisfreelancer@gmail.com',
            'phone' => '8014700382',
            'productinfo' => 'room2',
            'service_provider' => 'payu_paisa',
            'amount' => '100',

      ];

      // gateway = CCAvenue / PayUMoney / EBS / Citrus / InstaMojo

      $order = Indipay::gateway('PayUMoney')->prepare($parameters);
      return Indipay::process($order);
       
    
    }`
plz help me on the missing parameter

**Comment by softon** [comment]
oohhh. There is a validation in surl and furl it cannot be simple string it has to be url's.

by the way u need not pass those as parameters as they are inserted automatically by the package, u can use it only if u want to change the path. to configure the response url check the indipay config file. Line #65
