### ISSUE TITLE
Payment audit

### ISSUE THREAD

**Issue by akitengineer** [softon/indipay#19]
Hi ,

I am using Indipay package in laravel 5.1, I found it really awesome and easy to integrate module. But I have a query:

In my project its a requirement to track each state of payment, for example, when user click on pay now order will be created and its status will be marked as "Order initiated" and when the request completed I will log the response and marked the order status as "Order Success/Order failure" .

So the problem is I can not log the parameters created by Indipay package just before sending the request. I need to log all of the parameters created by PayUMoney gateway. So how do I achieve this thing. Please help! 

Thanks

**Comment by softon** [comment]
The prepare function gives the order details.

Before process function add ur logic to save the order status

**Comment by akitengineer** [comment]
Hi I found following methods in Indipay.php file:

/**
     * @param PaymentGatewayInterface $gateway
     */
    function __construct(PaymentGatewayInterface $gateway)
    {
        $this->gateway = $gateway;
    }

    public function purchase($parameters = array()){

        return $this->gateway->request($parameters)->send();

    }

    public function response($request)
    {
        return $this->gateway->response($request);
    }

I did not found any method named "prepare". So I think it will throw and exception.

**Comment by softon** [comment]
you must be using older version.
