### ISSUE TITLE
Usage in Controller gives an error

### ISSUE THREAD

**Issue by sujitrulz** [softon/indipay#20]
Hi, Can you please let me know the issue below:

> Non-static method Softon\Indipay\Indipay::gateway() should not be called statically, assuming $this from incompatible context

even though you have not made gateway() static, you are calling it statically and even after instantiating the Indipay Class like $order = new Indipay();  it gives error like below

> Argument 1 passed to Softon\Indipay\Indipay::__construct() must be an instance of Softon\Indipay\Gateways\PaymentGatewayInterface, none given, called in /var/www/public/avs/app/Http/Controllers/CartController.php on line 128 and defined

Can you help me out how do i pass PaymentGatewayInterface object while insantiating Indipay?

**Comment by softon** [comment]
Use Indipay facade to call the gateway. as shown in the README.md
