### ISSUE TITLE
Not able to use any gateway other than default one.

### ISSUE THREAD

**Issue by RealtimeSignalTech** [softon/indipay#22]
Even if I mention gateway other than default one, it is taking default one only. Please let me know what could be the issue.

        return Indipay::process($order); // default
        return Indipay::gateway('ccavenue')->process($order); // others

**Comment by softon** [comment]
Check the letter case of gateway. check the config file for the case. Like 

 // gateway = CCAvenue / PayUMoney / EBS / Citrus / InstaMojo
