### ISSUE TITLE
PayUMoney Integration

### ISSUE THREAD

**Issue by Arvind8858** [softon/indipay#23]
I am trying to integrate my payumoney gateway in my laravel application but its showing me error when I am going to make payment. Do I need to get any activation key from Softon/Indipay service provider for activate this API for use? If yes then tell me how I can get that API activation Key?

**Comment by softon** [comment]
just get the key from payumoney and add it to the config file.

**Comment by bhanushalimahesh3** [comment]
@Arvind8858 what error are you getting?? some key is missing is that the error are you getting??

**Comment by bhanushalimahesh3** [comment]
@softon please update your document. I got key missing error while integrating it for payumoney
$parameters = [
    	   
    	     'tid' => '1233221223322',    	     
    	     'order_id' => '1232212',    	     
    	     'amount' => '1200.00',
    	     'firstname' => 'test',
    	     'email' => abc@gmail.com',
    	     'phone' => '1234567890',
    	     'productinfo' => 'testing',    	     
    	   ];
without firstname, email, phone, productinfo key it's throwing error, as those fields are required fields

**Comment by softon** [comment]
The required field changes from provider to provider. This is a common api for many gateways. Required parameters need to be passed on based on your choice of gateway.

**Comment by narendraraghuwanshi** [comment]
I have also problem with payumoney its getting me some error occured
![image](https://cloud.githubusercontent.com/assets/26792935/24504166/c91be6be-1572-11e7-999a-dc7046d9d48f.png)

**Comment by bhanushalimahesh3** [comment]
@narendraraghuwanshi looks configuration issue. Did you try payumoney test link.

**Comment by rakeshAcharya1234** [comment]
could anyone please help me how to configure for test payumoney ?

**Comment by softon** [comment]
In the config file enable test mode

'testMode'  => true,

**Comment by ankitabhatti05** [comment]
@softon @bhanushalimahesh3 I am passing all the required field and but at I can not move further because of below blade issue 

![Screenshot_2](https://user-images.githubusercontent.com/41182347/83516523-d9b95a00-a4f4-11ea-81f8-53dee69471bb.png)

this functionality does not work for me ="{{ $parameters['curl'] or '' }}

Please help me to get out of this error.

Thank you.
