### ISSUE TITLE
Call to undefined function Softon\Indipay\Gateways\mcrypt_module_open()

### ISSUE THREAD

**Issue by man9035206** [softon/indipay#29]
How to fix this Error Call to undefined function Softon\Indipay\Gateways\mcrypt_module_open()

**Comment by softon** [comment]
PHP must be compiled with mcrypt.

**Comment by man9035206** [comment]
Ok fine i have fixed it,
From where can i get merchant id,access code and working key,Thank you.

**Comment by softon** [comment]
from your admin panel @ ccavenue

**Comment by bhalsodkhushal** [comment]
How to fix below error on PHP 7.1 ?

Function mcrypt_module_open() is deprecated.

**Comment by gopal-g** [comment]
You cant fix this issue! mcrypt_* functions are deprecated for a cause * SECURITY VULNERABILITY*  I have raised a ticket to CCAvenue to fix this they are sleeping since 2 weeks. Useless Gateway!

**Comment by gopal-g** [comment]
### Update 

CCavenue has released their latest SDK for the same now we are able to integrate it on PHP 7.1 you can use my own package for the same [gopal-g/payment](https://github.com/gopal-g/payment). It is very much similar to this package.

**Comment by sumandeveloperonrent** [comment]
> Ok fine i have fixed it,
> How to get ccavenue merchant id,access code and working key,Thank you.

How did u fix this issue please explain

**Comment by softon** [comment]
Resolved in the latest version

**Comment by bhavanatamhankar** [comment]
Still getting same error for laravel 5.8, php 7.2. Updated composer to get latest version of this library

**Comment by jomonthomaslobo** [comment]
No luck.

**Comment by expertmile123** [comment]
> How to fix this Error Call to undefined function Softon\Indipay\Gateways\mcrypt_module_open()

Hi,
I AM ALSO FACING PROBLEM, GETTING SAME ERROR. Can you suggest solution. Thanks
