### ISSUE TITLE
Error while trying to install this package via composer 

### ISSUE THREAD

**Issue by sudipta26889** [softon/indipay#3]
I always got this error while trying to install this package via composer 
"Your requirements could not be resolved to an installable set of packages."
I am Using version ^0.0.4 for softon/indipay
![screenshot from 2015-10-01 22 01 13](https://cloud.githubusercontent.com/assets/5617675/10226999/988747e8-6888-11e5-87da-16b3d9153372.png)

**Comment by softon** [comment]
check your laravel version it is 5.1

this package is for laravel 5.0

**Comment by dixitchopra** [comment]
Could you please come up for 5.1?
