### ISSUE TITLE
Class Softon\Indipay\Gateways\ccavenueGateway does not exist

### ISSUE THREAD

**Issue by dattz** [softon/indipay#32]
I'm getting this error:
```
(1/1) ReflectionException
Class Softon\Indipay\Gateways\ccavenueGateway does not exist
```
![image](https://user-images.githubusercontent.com/6032048/28500905-9aada520-6fee-11e7-982e-09c4f3550a6c.png)

My indipay.php config file has this:
```
    'gateway' => 'ccavenue',                // Replace with the name of default gateway you want to use

    'testMode'  => true,                   // True for Testing the Gateway [For production false]

    'ccavenue' => [                         // CCAvenue Parameters
        'merchantId'  => #####,
        'accessCode'  => #####,
        'workingKey' => #####,

        // Should be route address for url() function
        'redirectUrl' => env('INDIPAY_REDIRECT_URL', 'indipay/response'),
        'cancelUrl' => env('INDIPAY_CANCEL_URL', 'indipay/response'),

        'currency' => env('INDIPAY_CURRENCY', 'INR'),
        'language' => env('INDIPAY_LANGUAGE', 'EN'),
    ],
```

It seems this works on my local system (mac) and doesn't work on an ubuntu server. I think it may be a case sensitive file naming issue. It's looking for the class name "ccavenueGateway", however the class that exists is "CCAvenueGateway" in CCAvenueGateway.php file. It makes sense that it works on mac (my filesystem is not case sensitive) and doesn't work on ubuntu (case sensitive?).

Please help.

**Comment by dattz** [comment]
I changed the CCAvenueGateway.php file /vendor/softon/indipay/src/Gateways to ccavenueGateway.php and also changed the class name to "ccavenueGateway", it now detects the class.

(Now i'm at: 
`(1/1) FatalThrowableErrorCall to undefined function Softon\Indipay\Gateways\mcrypt_module_open()
`
but this error isn't related to the issue at hand)

**Comment by dattz** [comment]
What's the resolution here? I shouldn't be changing the files under /vendor directory. What's the correct way? or what am I doing wrong?

**Comment by softon** [comment]
gateway = CCAvenue / PayUMoney / EBS / Citrus / InstaMojo

Name of the gateway should be one of this as mentioned in the readme

**Comment by dattz** [comment]
I set it as ccavenue only.

**Comment by softon** [comment]
it should be CCAvenue and not ccavenue. Check caps.
