### ISSUE TITLE
Error Code: 10001     Invalid Request - Encrypted request invalid/not present.

### ISSUE THREAD

**Issue by salmanakhatar** [softon/indipay#36]
I followed the exact steps and also made a request to CCAvenue for adding the URL. Later I got new access code as well as working key.
Now I am facing the following error:

`Error Code: 10001     Invalid Request - Encrypted request invalid/not present.
Don't worry... It happens to the best of us.`

What could be wrong?

**Comment by softon** [comment]
check the required fields for the gateway you are using.
