### ISSUE TITLE
How to get RSA?

### ISSUE THREAD

**Issue by sbasu80** [softon/indipay#40]
How to get RSA key from php server for integrating with android?
I tried but it sends error 
!ERROR!Caller IP not registered/Merchant Not found.

**Comment by softon** [comment]
Sorry for the late reply. was caught up with some projects. This implementation is to be used with web based app. so you may use a webview in android.

**Comment by IMHitesh** [comment]
Please use 
https://test.ccavenue.com/transaction/getRSAKey instead of https://secure.ccavenue.com/transaction/getRSAKey

**Comment by kesamani** [comment]
hey  its working thank you @IMHitesh

**Comment by IMHitesh** [comment]
> hey its working thank you @IMHitesh

Glad to hear that!!

**Comment by sinhabiswajit** [comment]
Hello @IMHitesh 
I am getting Error 10001 Invalid request-Encrypted request invalid/not present. I am using the mobile kit android code of their apk file(non seamless). The four files cacert.pem, ccavResponseHandler.php, Crypto.php, and GetRSA.php have been stored on the same directory in my web server. I am using https://test.ccavenue.com/transaction/getRSAKey in my GetRSA.php file. What could be the issue? I am using the accesscode, merchant key and working key provided by CCAvenue team for web kit and I just logged into merchant account in CCAvenue page and downloaded mobile kit.

**_Constants file in my android app :_** 
public class Constants {
	public static final String PARAMETER_SEP = "&";
	public static final String PARAMETER_EQUALS = "=";
	public static final String TRANS_URL = "https://test.ccavenue.com/transaction/transaction.docommand=initiateTransaction";
	public static final String access_code = "xxxxxxx87AJxxxxxx"; // add your access_code
	public static final String merchantId= "173xxxx"; // add your merchant_id
	public static final String currency="INR";
	public static final String redirectUrl="http://xxxxxxxxx.com/testproject1/app_ccavenue/PHP/ccavResponseHandler.php"; 
	public static final String cancelUrl="http://xxxxxxxxx.com/testproject1/app_ccavenue/PHP/ccavResponseHandler.php"; 
	public static final String rsaKeyUrl="http://xxxxxxxxx.com/testproject1/app_ccavenue/PHP/GetRSA.php"; 


_**My GetRSA.php file in my web server:**_ 


<?php
$url = "https://test.ccavenue.com/transaction/getRSAKey";
$fields = array(
        'access_code'=>"xxxx04KE87xxxxxxxx",
        'order_id'=>$_POST['order_id']
);

$postvars='';
$sep='';
foreach($fields as $key=>$value)
{
        $postvars.= $sep.urlencode($key).'='.urlencode($value);
        $sep='&';
}

$ch = curl_init();

curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_POST,count($fields));
curl_setopt($ch, CURLOPT_CAINFO, 'cacert.pem');
curl_setopt($ch,CURLOPT_POSTFIELDS,$postvars);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$result = curl_exec($ch);

echo $result;
?>
