### ISSUE TITLE
encrypt() and decrypt() is not working for CCAvenue driver since PHP 7.1

### ISSUE THREAD

**Issue by dakshhmehta** [softon/indipay#44]
The encrypt function and decrypt function is using the hardcoded value of MCRYPT_RIJNDAEL cipher, which is not valid after PHP7.0

So, the alternative solution to using config('app.cipher'); is requested to be implemented. Or I don't know how these functions are used, but can't we simply use encrypt() and decrypt() helper function of Laravel Crypt class?

This needs to be resolved ASAP!

cc: @softon

**Comment by gopal-g** [comment]
Hi, I am a victim of this issue and it was due to outdated code from ccavenue side, Please use my package which is a fork of this very own package but has the latest CCAvenue SDK integrated which helps fix encrypt and decrypt issues. 

https://github.com/gopal-g/payment

**Comment by hardevine** [comment]
having same issue here trying @gopal-g

**Comment by hardevine** [comment]
@softon when it will be resolved. @gopal-g can you make a PR so we can update this package ?

**Comment by bassi-avi** [comment]
Fix This folks .. ??

@gopal-g Your package does not work properly at step 4. 
reflectionexception in container.php line 749: class view does not exist

@dakshhmehta : any resolution?

**Comment by gopal-g** [comment]
@bassi-avi  I request you to post more information related to the error in my github page along with screen shot of the debug information while running vendor:publish .

**Comment by gopal-g** [comment]
@tanmay27vats i encourage you to try my package which uses the latest PHP SDK of CCAvenue. [https://github.com/gopal-g/payment](url)

**Comment by hardevine** [comment]
@gopal-g how to do recurring payments in https://github.com/gopal-g/payment

**Comment by tanmay27vats** [comment]
@gopal-g sounds good. But https://github.com/softon/indipay/issues/44#issuecomment-415998599 this user is reporting an issue on your package. Is it still there or you have resolved it?

**Comment by tanmay27vats** [comment]
@gopal-g sure I will share my feedback once I use your package.

**Comment by gopal-g** [comment]
> @gopal-g how to do recurring payments in https://github.com/gopal-g/payment

I do not see that as a generic requirement hence it is not possible with my package. The purpose of that package is to delegate between your application and ccavenue for a single payment. Ofcourse you can code it in such a way that you make

**Comment by softon** [comment]
resolved
