### ISSUE TITLE
issue on Linux servers. Please test your package on Linux servers. Errors on naming files.

### ISSUE THREAD

**Issue by kuldeept010** [softon/indipay#46]
Linux is case-sensitive and the Files in 

> src/Gateways/ 

are not named properly. Windows is case-insensitive and the package works completely fine on it. On Linux it will put an 

> ClassNotFoundException

Please make sure your names are correct for each payment gateway. And the package is completely tested on linux mahines.

>

**Comment by softon** [comment]
The packages are completely tested. please read the indipay config file for the values to be used in the gateways/ the readme.md. thank you.
