### ISSUE TITLE
Merchant authintication failed

### ISSUE THREAD

**Issue by sivakaza** [softon/indipay#5]
Hi,

I'm using L5.1 and i have installed indipay successfully. but while connecting to test environment (https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction) with the credentials i'm getting the following errors. 

Error Code: 10002     Merchant Authentication failed.
Don't worry... It happens to the best of us. 

Not able to figure out what might be the issue.

**Comment by softon** [comment]
Your credentials are incorrect or the account is not activated. I mean the test account. you will need to ask them to enable it. yeah test account need to be activated separately.

**Comment by sivakaza** [comment]
@softon Thanks for the quick response.  In my case the issue is they haven’t activated the account yet. Just i requested them to activate it.

**Comment by kapil11Agnihotri** [comment]
In my case my credential perfectly working on HTML page ,but when i am using in my React app its giving me 10002 Error..Can anyone help me .
