### ISSUE TITLE
After  return Indipay::process($order) page goes blank

### ISSUE THREAD

**Issue by sujith2014** [softon/indipay#54]
```
   $parameters = [
      
        'tid' => '1233221223322',
        
        'order_id' => '1232212',
        
        'amount' => '1200.00',
        
      ];
       
      $order = Indipay::gateway('PayUMoney')->prepare($parameters);
    //dd(Indipay::process($order)); displaying output
      return Indipay::process($order);
```
dd(Indipay::process($order));  displaying output.
But after commenting dd(Indipay::process($order));  
page goes blank without any error.

**Comment by softon** [comment]
cannot debug unless debug info is provided. Please enable app_debug and check log file too for any errors.

**Comment by divyesh210792** [comment]
@sujith2014 
I am facing same issue, Did you find any solution for it?

**Comment by sujith2014** [comment]
When I use same function for all the paymet it works fine.

**Comment by divyesh210792** [comment]
@sujith2014 
Did it work for ccavenu?

**Comment by velmurugan1996** [comment]
yes

**Comment by softon** [comment]
you should check the view page source and find what the page is generating. maybe javascript is disabled. if anyone still has a problem.
