### ISSUE TITLE
PHPUnit Testing TokenMismatch Exception

### ISSUE THREAD

**Issue by MehulBawadia** [softon/indipay#56]
After installing this package succesfully and running the test suite, the application blows up with errors:

`TokenMismatchException`.

After an hour of digging into the code, here's what you need to do..

Open the middleware that comes with this package, i.e., `VerifyCsrfMiddleware` and inside the `handle` method has an `if` statement.

Earlier:
```
if (
    $this->isReading($request) || 
    $this->excludedRoutes($request) || 
    $this->tokensMatch($request)
) {
    return $this->addCookieToResponse($request, $next($request));
}
```
There is a missing method here.. That method is `runningUnitTests()` which is located in `\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken` file. You need to add it to the `if` statement, like so..

```
if (
    $this->isReading($request) || 
    $this->excludedRoutes($request) || 
    $this->tokensMatch($request) || 
    $this->runningUnitTests()
) {
    return $this->addCookieToResponse($request, $next($request));
}
```

With this minor edit, you can run the entire test suite again.

Silly point.. But should help the new comers who will use this package..

Hope this helps.

**Comment by softon** [comment]
@MehulBawadia thanks for the input. updated the middleware code.
