### ISSUE TITLE
Payout Feature

### ISSUE THREAD

**Issue by amol-c** [softon/indipay#6]
Hey @softon,

Nice to see the library. Can you add a feature for payout as well ? That will be very handy.

http://www.citruspay.com/DevelopersGuide/splitpay/payout.html

Thanks,
Amol

**Comment by softon** [comment]
Payout in most cases is automatic except for some gateways. So this will not be feasible to implement for a single gateway.

**Comment by amol-c** [comment]
Which gateway do u recommend for payout ?

**Comment by softon** [comment]
PayUMoney is my favourite.
