### ISSUE TITLE
Class Softon\Indipay\Gateways\Gateway does not exist

### ISSUE THREAD

**Issue by ankitabhatti05** [softon/indipay#66]
$input = [
            'transaction_id' => '454554545',
            'order_id' => '654654564',
            'amount' => '1.0'
        ];
        
$order = Indipay::gateway('CCAvenue')->prepare($input);
        return Indipay::process($order);
I have used the above code but still i am getting 
> Class Softon\Indipay\Gateways\Gateway does not exist error

**Comment by TheFreeman15** [comment]
Found any fix regarding this ? @ankitabhatti05

**Comment by TheFreeman15** [comment]
Found a fix just run php artisan:config cache after installing

**Comment by softon** [comment]
@ankitabhatti05  is the issue solved?
