### ISSUE TITLE
Can not pay payumoney gateway because of laravel blade file's function

### ISSUE THREAD

**Issue by ankitabhatti05** [softon/indipay#67]
@softon @bhanushalimahesh3 I am passing all the required fields but I can not move further because of the below blade issue.

I am using Laravel 5.7 version if the blade templates "or" functionality is not working for laravel 5.7 then please give us the functionality that supports laravel 5.7 version.

![Screenshot_2](https://user-images.githubusercontent.com/41182347/83516523-d9b95a00-a4f4-11ea-81f8-53dee69471bb.png)

this functionality does not work for me ="{{ $parameters['curl'] or '' }}

Or please help me to pass parameter values like what will be the values of curl, udf1, udf2, udf3, udf4, udf5, pg.

Please help me to get out of this error.

Thank you.

_Originally posted by @ankitabhatti05 in https://github.com/softon/indipay/issues/23#issuecomment-637490657_

**Comment by bhanushalimahesh3** [comment]
@ankitabhatti05 try setting them empty '' string. Looks package has support till 5.5

**Comment by ankitabhatti05** [comment]
> @ankitabhatti05 try setting them empty '' string.

I have tried that but not worked for me.

**Comment by softon** [comment]
removed or and replased with ?:
