### ISSUE TITLE
Can I integrate PayUBiz Payment gateway in same ?

### ISSUE THREAD

**Issue by sanmitpawar** [softon/indipay#70]
Hello, i am sanmit pawar.

In one of our project we have PayUBiz Payment Gateway Account, can I integrate PayUBiz in from the same package, if yes can I use PayUMoney configuration for PayUBiz or there is any other way.

please revert on the same.

**Comment by softon** [comment]
Oh that will be great. You can send a pull request.

**Comment by sanmitpawar** [comment]
> Oh that will be great. You can send a pull request.

sorry, sir, I don't know how to send a pull request I just need is it supported in the same package. and if yes how I can integrate please guide me for the same. 

Thank you!

**Comment by softon** [comment]
oh no problem. you can share the integration docs to my email and we will try to integrate it. powerupneo@gmail.com
